# Generated by Django 4.2.1 on 2023-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='has_empty',
            field=models.BooleanField(default=True),
        ),
    ]
