# Generated by Django 4.2.1 on 2023-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(unique=True)),
                ('has_empty', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
