# Generated by Django 4.2.1 on 2023-05-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('reservation', '0009_alter_payment_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='room.room'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
