# Generated by Django 4.2.1 on 2023-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
